-- Seed data from Excel
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (42638.0, 'PTG', 'Chaiya-059-01', 'Chaiya Tamane', 49.19, 'ACTIVE');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (6954.0, 'PTG', 'Chaiya-059-02', 'Chaiya Tamane', 10.41, 'ACTIVE');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (6955.0, 'PTG', 'Chaiya-059-03', 'Chaiya Tamane', 10.36, 'ACTIVE');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (6763.0, 'PTG', 'Chalong-031-01', 'Chalong Thongsopha', 9.9, 'ACTIVE');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (27376.0, 'PTG', 'Chalong-031-02', 'Chalong Thongsopha', 13.36, 'ACTIVE');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (42379.0, 'PTG', 'Chalong-031-03', 'Chalong Thongsopha', 5.95, 'ACTIVE');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (42378.0, 'PTG', 'Chalong-031-04', 'Chalong Thongsopha', 2.65, 'ACTIVE');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (36260.0, 'PTG', 'Chalong-031-05', 'Chalong Thongsopha', 8.64, 'ACTIVE');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (20851.0, 'PTG', 'Chalong-031-06', 'Chalong Thongsopha', 8.82, 'ACTIVE');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (29051.0, 'PTG', 'Duangkamon-005-01', 'Duangkamon Rungreuang', 8.6, 'ACTIVE');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (29032.0, 'PTG', 'Duangkamon-005-02', 'Duangkamon Rungreuang', 9.95, 'ACTIVE');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (36177.0, 'PTG', 'Duangkamon-005-03', 'Duangkamon Rungreuang', 6.52, 'ACTIVE');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (7185.0, 'PTG', 'Jamnian-004-01', 'Jamnian Thaya', 20.35, 'ACTIVE');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (36156.0, 'PTG', 'Kamphaorap-030-01', 'Kamphaorap Tamane', 12.97, 'ACTIVE');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (40382.0, 'PTG', 'Kamphaorap-030-02', 'Kamphaorap Tamane', 7.31, 'ACTIVE');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (33432.0, 'PTG', 'Kamphaorap-030-03', 'Kamphaorap Tamane', 7.24, 'ACTIVE');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (7273.0, 'PTG', 'Kamphaorap-030-04', 'Kamphaorap Tamane', 8.6, 'ACTIVE');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (39064.0, 'PTG', 'Kamphaorap-030-05', 'Kamphaorap Tamane', 5.01, 'ACTIVE');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (36137.0, 'PTG', 'Kamphaorap-030-06', 'Kamphaorap Tamane', 5.3, 'ACTIVE');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (20844.0, 'PTG', 'Kamphaorap-030-07', 'Kamphaorap Tamane', 16.94, 'ACTIVE');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (28849.0, 'PTG', 'Kanyaa-001-01', 'Kanyaa Khemngoen', 8.16, 'ACTIVE');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (27103.0, 'PTG', 'Laemthong-027-01', 'Laemthong Boonchuay', 4.5, 'ACTIVE');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (28927.0, 'PTG', 'Lukkid-016-01', 'Lukkid Wangngam', 6.26, 'ACTIVE');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (7274.0, 'PTG', 'Manee-032-01', 'Manee Thongsopha', 4.67, 'ACTIVE');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (36259.0, 'PTG', 'Manee-032-02', 'Manee Thongsopha', 17.7, 'ACTIVE');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (42380.0, 'PTG', 'Manee-032-03', 'Manee Thongsopha', 5.88, 'ACTIVE');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (42377.0, 'PTG', 'Manee-032-04', 'Manee Thongsopha', 2.67, 'ACTIVE');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (17333.0, 'PTG', '', '', 2.34, 'ACTIVE');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (29054.0, 'PTG', '', '', 10.51, 'ACTIVE');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (35736.0, 'PTG', '', '', 4.71, 'ACTIVE');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (36044.0, 'PTG', '', '', 6.78, 'ACTIVE');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (40122.0, 'PTG', '', '', 7.1, 'ACTIVE');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (45828.0, 'PTG', '', '', 6.37, 'ACTIVE');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (27054.0, 'PTG', '', '', 19.26, 'ACTIVE');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (7247.0, 'PTG', '', '', 13.67, 'ACTIVE');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (31279.0, 'PTG', '', '', 2.24, 'ACTIVE');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (42800.0, 'PTG', '', '', 3.88, 'ACTIVE');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (7084.0, 'PTG', '', '', 23.05, 'ACTIVE');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (17340.0, 'PTG', '', '', 2.59, 'ACTIVE');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (20846.0, 'PTG', '', '', 9.95, 'ACTIVE');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (32435.0, 'PTG', '', '', 5.12, 'ACTIVE');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (27100.0, 'PTG', '', '', 7.6, 'ACTIVE');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (16142.0, 'CPA6', '', '', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (28812.0, 'CPA6', '', '', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (18334.0, 'CPA6', '', '', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (3013.0, 'CPA6', '', '', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (37237.0, 'CPA6', 'Anek-096-01', 'Anek Salipol', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (37236.0, 'CPA6', 'Anek-096-02', 'Anek Salipol', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (14052.0, 'CPA6', 'Phairo-099-04', 'Phairo Phookang', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (19055.0, 'CPA6', 'Phairo-099-02', 'Phairo Phookang', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (21362.0, 'CPA6', 'Phairo-099-01', 'Phairo Phookang', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (28386.0, 'CPA6', 'Phairo-099-03', 'Phairo Phookang', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (44450.0, 'CPA6', 'Phairo-099-05', 'Phairo Phookang', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (37234.0, 'CPA6', 'Khan-095-01', 'Khan Salipon', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (34054.0, 'CPA6', 'ChanPhen-090-02', 'ChanPhen MaKhong', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (6503.0, 'CPA6', 'ChanPhen-090-01', 'ChanPhen MaKhong', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (39190.0, 'CPA6', 'Chaba-046-03', 'Chaba Klaimala', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (39208.0, 'CPA6', 'Chaba-046-02', 'Chaba Klaimala', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (28811.0, 'CPA6', '', '', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (31171.0, 'CPA6', '', '', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (32458.0, 'CPA6', '', '', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (3106.0, 'CPA6', '', '', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (30971.0, 'CPA6', 'Turean-029-03', 'Turean Sripiangchan', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (3220.0, 'CPA6', 'Thanalot-100-01', 'Thanalot Chaitonpatkul', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (43614.0, 'CPA6', 'Thanalot-100-02', 'Thanalot Chaitonpatkul', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (13247.0, 'CPA6', 'Phanom-089-03', 'Phanom NiyomThong', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (15787.0, 'CPA6', 'Phanom-089-04', 'Phanom NiyomThong', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (21367.0, 'CPA6', 'Phanom-089-01', 'Phanom NiyomThong', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (3233.0, 'CPA6', 'Phanom-089-02', 'Phanom NiyomThong', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (34266.0, 'CPA6', 'Yurapat-038-03', 'Yurapat Rodcheanglam', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (7146.0, 'CPA6', 'Yurapat-038-02', 'Yurapat Rodcheanglam', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (28080.0, 'CPA3', 'Paengfung-054-01', 'Paengfung Kritsawong', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (32142.0, 'CPA3', 'Somjit-088-01', 'Somjit Thanyacharoen', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (27062.0, 'CPA4', 'Laemthong-083-01', 'Laemthong Boonchuay', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (27064.0, 'CPA4', 'Laemthong-083-02', 'Laemthong Boonchuay', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (27065.0, 'CPA4', 'Laemthong-083-03', 'Laemthong Boonchuay', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (17343.0, 'CPA4', 'Sorat-075-03', 'Sorat NutNat', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (17344.0, 'CPA4', 'Sorat-075-02', 'Sorat NutNat', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (34441.0, 'CPA4', 'Sorat-075-04', 'Sorat NutNat', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (38016.0, 'CPA4', 'Sorat-075-01', 'Sorat NutNat', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (35602.0, 'CPA4', 'Kanyaa-053-01', 'Kanyaa Khemngoen', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (6816.0, 'CPA4', 'Jamnian-071-03', 'Jamnian Thaya', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (88470.0, 'CPA4', 'Damrong-084-01', 'Damrong	Kanpatthan', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (9129.0, 'CPA4', 'Damrong-084-02', 'Damrong	Kanpatthan', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (59545.0, 'CPA4', 'Damrong-084-03', 'Damrong	Kanpatthan', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (47398.0, 'CPA4', 'Damrong-084-04', 'Damrong	Kanpatthan', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (38385.0, 'CPA4', 'Damrong-084-05', 'Damrong	Kanpatthan', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (6765.0, 'CPA4', 'Thongphun-087-01', 'Thongphun Soria-rya', 0, 'ACTIVE');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (15036.0, 'CPA4', 'PraKit-076-03', 'PraKit NutNat', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (20853.0, 'CPA4', 'PraKit-076-04', 'PraKit NutNat', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (33354.0, 'CPA4', 'PraKit-076-01', 'PraKit NutNat', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (44518.0, 'CPA4', 'PraKit-076-02', 'PraKit NutNat', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (7299.0, 'CPA4', 'Patama-074-01', 'Patama Amphon', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (10336.0, 'CPA1', 'Phettawan-016-02', 'Phettawan PhanTon', 9.68575, 'ACTIVE');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (13065.0, 'CPA1', 'Phettawan-016-01', 'Phettawan PhanTon', 1.7818125, 'ACTIVE');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (24899.0, 'CPA1', 'Phettawan-016-03', 'Phettawan PhanTon', 12.3229375, 'ACTIVE');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (36129.0, 'CPA4', 'Phayao-085-01', 'Phayao Phongam', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (20858.0, 'CPA4', 'Pissit-081-01', 'Pissit Kaliangprasert', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (31277.0, 'CPA4', 'Siroj-078-02', 'Siroj Onsiroj', 0, 'ACTIVE');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (31278.0, 'CPA4', 'Siroj-078-03', 'Siroj Onsiroj', 0, 'ACTIVE');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (34376.0, 'CPA4', 'Siroj-078-01', 'Siroj Onsiroj', 0, 'ACTIVE');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (36161.0, 'CPA4', 'Srinuan-082-01', 'Srinuan Ratree', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (35957.0, 'CPA4', 'Saad-068-06', 'Saad Rungreung', 0, 'ACTIVE');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (28796.0, 'CPA1', 'Phettawan-016-04', 'Phettawan PhanTon', 4.263625, 'ACTIVE');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (11794.0, 'CPA1', 'Reanu-013-02', 'Reanu Meebubpha', 12.064125, 'ACTIVE');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (9058.0, 'CPA4', 'Sumontha-019-01', 'Sumontha Phetkonchom', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (11795.0, 'CPA1', 'Reanu-013-03', 'Reanu Meebubpha', 6.2455, 'ACTIVE');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (17567.0, 'CPA4', 'Suriyan-023-01', 'Suriyan Hoythong', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (64066.0, 'CPA4', 'Suriyan-023-02', 'Suriyan Hoythong', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (86935.0, 'CPA4', 'Suriyan-023-03', 'Suriyan Hoythong', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (32433.0, 'CPA4', 'Uthai-079-01', 'Uthai Panyaporn', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (42429.0, 'CPA4', 'Ubon-080-01', 'Ubon Jeensuksaeng', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (6767.0, 'CPA4', 'Ubon-080-02', 'Ubon Jeensuksaeng', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (7286.0, 'CPA4', 'Ubon-080-03', 'Ubon Jeensuksaeng', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (28081.0, 'CPA3', 'Paengfung-054-02', 'Paengfung Kritsawong', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (34254.0, 'CPA3', 'Paengfung-054-03', 'Paengfung Kritsawong', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (33601.0, 'CPA3', 'Kanyaa-053-01', 'Kanyaa Khemngoen', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (33600.0, 'CPA3', 'Kanyaa-053-02', 'Kanyaa Khemngoen', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (33599.0, 'CPA3', 'Kanyaa-053-03', 'Kanyaa Khemngoen', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (19522.0, 'CPA3', 'Kamphaorap-057-01', 'Kamphaorap Tamane', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (20852.0, 'CPA3', 'Kamphaorap-057-01', 'Kamphaorap Tamane', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (42376.0, 'CPA3', 'Kamphaorap-057-02', 'Kamphaorap Tamane', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (47352.0, 'CPA3', 'Jamnian-071-01', 'Jamnian Thaya', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (7290.0, 'CPA3', 'Jamnian-071-02', 'Jamnian Thaya', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (36176.0, 'CPA3', 'Duangkamon-063-01', 'Duangkamon Rungreuang', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (35665.0, 'CPA3', 'Namphueng-049-02', 'Namphueng Maitrakachorn', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (35663.0, 'CPA3', 'Namphueng-049-01', 'Namphueng Maitrakachorn', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (7992.0, 'CPA3', 'Namphueng-049-03', 'Namphueng Maitrakachorn', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (6861.0, 'CPA3', 'Boonchu-069-01', 'Boonchu Namkaeo', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (7213.0, 'CPA3', 'Patama-074-01', 'Patama Amphon', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (33229.0, 'CPA3', 'Patama-074-02', 'Patama Amphon', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (2859.0, 'CPA3', 'Pongsak-058-01', 'Suthasinee Meechana', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (2860.0, 'CPA3', 'Pongsak-058-02', 'Suthasinee Meechana', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (2882.0, 'CPA3', 'Phonapha-052-01', 'Phonapha Insawang', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (37547.0, 'CPA3', 'Phonapha-052-02', 'Phonapha Insawang', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (6962.0, 'CPA3', 'Phonapha-052-03', 'Phonapha Insawang', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (7287.0, 'CPA3', 'Phonsiri-073-01', 'Phonsiri Tamane', 0, 'ACTIVE');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (20767.0, 'CPA3', 'Lukkid-060-01', 'Lukkid Wangngam', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (20832.0, 'CPA3', 'Wanpen-062-01', 'Wanpen Thanyacharoen', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (36114.0, 'CPA3', 'Wanpen-062-02', 'Wanpen Thanyacharoen', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (43103.0, 'CPA3', 'Somchit-051-01', 'Somchit Kongkaew', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (4748.0, 'CPA3', 'Somchit-051-02', 'Somchit Kongkaew', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (36017.0, 'CPA3', 'Somsuan-055-01', 'Somsuan	Promjantha', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (35621.0, 'CPA3', 'Somsuan-055-02', 'Somsuan	Promjantha', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (46041.0, 'CPA3', 'Sommai-066-01', 'Sommai Intapho', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (20842.0, 'CPA3', 'Saad-068-05', 'Saad Rungreung', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (25604.0, 'CPA3', 'Saad-068-02', 'Saad Rungreung', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (28408.0, 'CPA3', 'Saad-068-04', 'Saad Rungreung', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (7211.0, 'CPA3', 'Saad-068-01', 'Saad Rungreung', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (7251.0, 'CPA3', 'Saad-068-03', 'Saad Rungreung', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (20898.0, 'CPA3', 'Suchip-061-01', 'Suchip Srisawasdi', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (6787.0, 'CPA3', 'Suphatra-070-01', 'Suthasinee Meechana', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (7176.0, 'CPA2', 'Kanyarat-039-01', 'Kanyarat Rungrangsi', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (6446.0, 'CPA2', 'Chaba-046-01', 'Chaba Klaimala', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (38328.0, 'CPA2', 'Turean-029-01', 'Turean Sripiangchan', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (43261.0, 'CPA2', 'Turean-029-02', 'Turean Sripiangchan', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (13120.0, 'CPA2', 'Boonchu-031-03', 'Boonchu Kraikaew', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (32597.0, 'CPA2', 'Boonchu-031-01', 'Boonchu Kraikaew', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (8682.0, 'CPA2', 'Boonchu-031-02', 'Boonchu Kraikaew', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (8610.0, 'CPA2', 'Prapai-042-01', 'Prapai Topha', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (11541.0, 'CPA2', 'Prapassri-034-01', 'Prapassri Rotsheunglum', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (13814.0, 'CPA2', 'Yongyut-045-02', 'Yongyut Phurang', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (3562.0, 'CPA2', 'Yongyut-045-03', 'Yongyut Phurang', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (6447.0, 'CPA2', 'Yongyut-045-01', 'Yongyut Phurang', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (7176.0, 'CPA2', 'Yurapat-038-01', 'Yurapat Rodcheanglam', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (7176.0, 'CPA2', 'Yurapat-038-01', 'Yurapat Rodcheanglam', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (23104.0, 'CPA2', 'Rampheay-043-01', 'Rampheay Saneewong-na-Ayutthaya', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (6272.0, 'CPA2', 'Rampheay-043-02', 'Rampheay Saneewong-na-Ayutthaya', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (6272.0, 'CPA2', 'Rampheay-043-02', 'Rampheay Saneewong-na-Ayutthaya', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (10659.0, 'CPA2', 'Rung-032-01', 'Rung Khun-ang-dee', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (11167.0, 'CPA2', 'Rung-032-04', 'Rung Khun-ang-dee', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (26924.0, 'CPA2', 'Rung-032-02', 'Rung Khun-ang-dee', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (33384.0, 'CPA2', 'Rung-032-03', 'Rung Khun-ang-dee', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (26925.0, 'CPA2', 'Rung-032-05', 'Rung Khun-ang-dee', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (26922.0, 'CPA2', 'Rung-032-06', 'Rung Khun-ang-dee', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (26923.0, 'CPA2', 'Rung-032-07', 'Rung Khun-ang-dee', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (19190.0, 'CPA2', 'Lamyai-037-01', 'Lamyai Thepnarong', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (8711.0, 'CPA2', 'Lamyai-037-02', 'Lamyai Thepnarong', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (7176.0, 'CPA2', 'Wasana-036-01', 'Wasana Wutthat', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (19190.0, 'CPA2', 'Somjet-030-03', 'Somjet Sombatcharoen', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (19192.0, 'CPA2', 'Somjet-030-02', 'Somjet Sombatcharoen', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (14957.0, 'CPA2', 'Somjet-030-01', 'Somjet Sombatcharoen', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (35841.0, 'CPA2', 'Sakorn-047-02', 'Sakorn Sombatjaroen', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (35842.0, 'CPA2', 'Sakorn-047-01', 'Sakorn Sombatjaroen', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (19190.0, 'CPA2', 'Saichon-027-03', 'Saichon Khunpakkadee', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (19191.0, 'CPA2', 'Saichon-027-01', 'Saichon Khunpakkadee', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (19192.0, 'CPA2', 'Saichon-027-02', 'Saichon Khunpakkadee', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (17085.0, 'CPA2', 'Suriya-028-01', 'Suriya Saenwong-na-Ayutthaya', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (6443.0, 'CPA2', 'Suwat-044-01', 'Suwat Phurang', 0, 'ACTIVE');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (42354.0, 'CPA2', 'Suwat-044-02', 'Suwat Phurang', 0, 'ACTIVE');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (6442.0, 'CPA2', 'Suwat-044-03', 'Suwat Phurang', 0, 'ACTIVE');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (38125.0, 'CPA2', 'Hoon-041-01', 'Hoon Rodcheanglam', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (38126.0, 'CPA2', 'Hoon-041-02', 'Hoon Rodcheanglam', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (8143.0, 'CPA2', 'Hoon-041-03', 'Hoon Rodcheanglam', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (3397.0, 'CPA1', 'Reanu-013-01', 'Reanu Meebubpha', 5.834187500000001, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (17508.0, 'CPA1', 'Iang-015-01', 'Iang PhanTan', 9.525375, 'ACTIVE');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (30480.0, 'CPA1', 'Iang-015-02', 'Iang PhanTan', 13.318, 'ACTIVE');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (40593.0, 'CPA1', 'Sopha-008-01', 'Sopha ChuenArom', 7.693250000000001, 'ACTIVE');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (39923.0, 'CPA1', 'Chayada-026-01 (old)', 'Chayada Phanchai', 9.1093125, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (29034.0, 'CPA1', 'Chayada-026-02 (old)', 'Chayada Phanchai', 3.157125, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (12155.0, 'CPA1', 'Chayada-026-03 (old)', 'Chayada Phanchai', 5.5531875, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (623.0, 'CPA1', 'Chaoum-005-01', 'Chaoum Samsi', 3.018125, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (42672.0, 'CPA1', 'Chaoum-005-02', 'Chaoum Samsi', 5.828250000000001, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (11796.0, 'CPA1', 'Thitiphat-021-01', 'Thitiphat Meebubpha', 5.7075, 'ACTIVE');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (17695.0, 'CPA1', 'Thitiphat-021-03', 'Thitiphat Meebubpha', 2.892, 'ACTIVE');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (19687.0, 'CPA1', 'Thitiphat-021-02', 'Thitiphat Meebubpha', 8.7440625, 'ACTIVE');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (39741.0, 'CPA1', 'ThongSuk-007-05', 'ThongSuk KaenKoMon', 3.686, 'ACTIVE');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (614.0, 'CPA1', 'ThongSuk-007-01', 'ThongSuk KaenKoMon', 4.0750625, 'ACTIVE');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (39740.0, 'CPA1', 'ThongSuk-007-04', 'ThongSuk KaenKoMon', 1.996, 'ACTIVE');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (39739.0, 'CPA1', 'ThongSuk-007-03', 'ThongSuk KaenKoMon', 1.8321875, 'ACTIVE');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (39738.0, 'CPA1', 'ThongSuk-007-02', 'ThongSuk KaenKoMon', 0.574375, 'ACTIVE');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (44011.0, 'CPA1', 'Bang-on-024-01 (old)', 'Bang-on Huanbutta', 1.6091875, 'ACTIVE');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (44012.0, 'CPA1', 'Bang-on-024-03', 'Bang-on Huanbutta', 2.302625, 'ACTIVE');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (44013.0, 'CPA1', 'Bang-on-024-02 (old)', 'Bang-on Huanbutta', 2.4396875, 'ACTIVE');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (18844.0, 'CPA1', 'Prani-002-02', 'Prani WongWichan', 6.44275, 'ACTIVE');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (668.0, 'CPA1', 'Prani-002-01', 'Prani WongWichan', 5.341687500000001, 'ACTIVE');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (20639.0, 'CPA1', 'Prani-002-03', 'Prani WongWichan', 9.0889375, 'ACTIVE');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (64205.0, 'CPA1', 'Parichat-018-01', 'Parichat Ruangsawasdee', 0, 'ACTIVE');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (33891.0, 'CPA1', 'Parichat-018-02', 'Parichat Ruangsawasdee', 0, 'ACTIVE');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (8944.0, 'CPA1', 'Parichat-018-03', 'Parichat Ruangsawasdee', 0, 'ACTIVE');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (10856.0, 'CPA1', 'Parichat-018-05', 'Parichat Ruangsawasdee', 12.3376875, 'ACTIVE');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (12396.0, 'CPA1', 'Parichat-018-01', 'Parichat Ruangsawasdee', 21.14, 'ACTIVE');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (13832.0, 'CPA1', 'Parichat-018-02', 'Parichat Ruangsawasdee', 5.476687500000001, 'ACTIVE');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (13834.0, 'CPA1', 'Parichat-018-03', 'Parichat Ruangsawasdee', 7.8321875, 'ACTIVE');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (26562.0, 'CPA1', 'Parichat-018-04', 'Parichat Ruangsawasdee', 1.25, 'ACTIVE');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (9067.0, 'CPA1', 'Parichat-018-06', 'Parichat Ruangsawasdee', 7.06, 'ACTIVE');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (16114.0, 'CPA1', 'Porapak-025-01 (note use)', 'Porapak Prapap', 13.35525, 'ACTIVE');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (41503.0, 'CPA1', 'Porapak-025-02', 'Porapak Prapap', 9.862375, 'ACTIVE');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (28260.0, 'CPA1', 'Porapak-025-03', 'Porapak Prapap', 1.6204375, 'ACTIVE');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (20638.0, 'CPA1', 'PhonPhanom-003-01', 'PhonPhanom WongWichan', 6.0036875, 'ACTIVE');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (1383.0, 'CPA1', 'PhanSi-017-01', 'PhanSi KuNaThon', 24.2435, 'ACTIVE');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (12597.0, 'CPA1', 'Manas-022-01', 'Manas Chanthawat', 77.8065625, 'ACTIVE');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (42141.0, 'CPA1', 'Somboon-004-01', 'Somboon Srikhamthai', 7.402125, 'ACTIVE');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (613.0, 'CPA1', 'SomPhon-006-01', 'SomPhon KhanThaKhuan', 6.6094375, 'ACTIVE');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (40577.0, 'CPA1', 'SomPhon-006-02', 'SomPhon KhanThaKhuan', 5.867875, 'ACTIVE');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (43506.0, 'CPA1', 'SomPhon-006-03', 'SomPhon KhanThaKhuan', 2.203375, 'ACTIVE');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (15706.0, 'CPA1', 'Somphorn-020-03', 'Somphorn Nak-ek', 1.9316875, 'ACTIVE');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (16258.0, 'CPA1', 'Somphorn-020-04', 'Somphorn Nak-ek', 2.85025, 'ACTIVE');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (15460.0, 'CPA1', 'Somphorn-020-05', 'Somphorn Nak-ek', 10.824625, 'ACTIVE');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (4577.0, 'CPA1', 'Somphorn-020-01', 'Somphorn Nak-ek', 4.63825, 'ACTIVE');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (15736.0, 'CPA1', 'Somphorn-020-02', 'Somphorn Nak-ek', 5.764250000000001, 'ACTIVE');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (10606.0, 'CPA1', 'Sumontha-019-04', 'Sumontha Phetkonchom', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (15075.0, 'CPA1', 'Sumontha-019-03', 'Sumontha Phetkonchom', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (74678.0, 'CPA1', 'Sumontha-019-02', 'Sumontha Phetkonchom', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (19160.0, 'CPA1', 'Sumnat-019-01', 'Sumontha Phetkonchom', 6.2846875, 'ACTIVE');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (9105.0, 'CPA1', 'Suriyan-023-01', 'Suriyan Hoythong', 10.9415625, 'ACTIVE');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (44308.0, 'CPA5', 'Bang-on-024-04', 'Bang-on Huanbutta', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (29386.0, 'CPA5', 'Bang-on-024-05', 'Bang-on Huanbutta', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (9532.0, 'CPA5', 'Bang-on-024-06', 'Bang-on Huanbutta', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (44310.0, 'CPA5', 'Bang-on-024-07', 'Bang-on Huanbutta', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (44309.0, 'CPA5', 'Bang-on-024-08', 'Bang-on Huanbutta', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (17014.0, 'CPA5', 'Bang-on-024-10', 'Bang-on Huanbutta', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (44010.0, 'CPA5', 'Bang-on-024-09', 'Bang-on Huanbutta', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (3437.0, 'CPA5', 'Bang-on-024-12', 'Bang-on Huanbutta', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (42816.0, 'CPA5', 'Bang-on-024-11', 'Bang-on Huanbutta', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (3439.0, 'CPA5', 'Bang-on-024-13 (old)', 'Bang-on Huanbutta', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (42817.0, 'CPA5', 'Bang-on-024-14', 'Bang-on Huanbutta', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (2919.0, 'CPA5', 'Suphattra-058-01', 'Suphatra Meechana', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (41447.0, 'CPA5', 'Sombut-001-01', 'Sombut Malinin', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (34899.0, 'CPA5', 'Sombut-001-02', 'Sombut Malinin', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (34900.0, 'CPA5', 'Sombut-001-03', 'Sombut Malinin', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (1919.0, 'CPA5', 'Sombut-001-04', 'Sombut Malinin', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (1926.0, 'CPA5', 'Sombut-001-05', 'Sombut Malinin', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (0, '', 'Boonleat-056-01', 'Chaiya Tamane', 0, '');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (36043.0, 'PTG', '', '', 2.8, 'ACTIVE');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (27059.0, 'PTG', 'Namthip-006-01', 'Namthip Taengsopha', 8.79, 'ACTIVE');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (0, '', 'Monas-072-01', 'Chaiya Tamane', 0, '');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (29052.0, 'PTG', 'Namthip-006-02', 'Namthip Taengsopha', 2.93, 'ACTIVE');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (27060.0, 'PTG', 'Namthip-006-03', 'Namthip Taengsopha', 12.32, 'ACTIVE');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (36142.0, 'PTG', 'Patama-007-02', 'Patama Amphon', 2.05, 'ACTIVE');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (41051.0, 'PTG', 'Phayao-012-01', 'Phayao Phongam', 1.94, 'ACTIVE');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (36151.0, 'PTG', 'Phayao-012-02', 'Phayao Phongam', 4.87, 'ACTIVE');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (36152.0, 'PTG', 'Phayao-012-03', 'Phayao Phongam', 5.16, 'ACTIVE');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (36150.0, 'PTG', 'Phayao-012-04', 'Phayao Phongam', 1.82, 'ACTIVE');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (7250.0, 'PTG', 'Phonapha-010-01', 'Phonapha Insawang', 7.37, 'ACTIVE');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (3072.0, 'PTG', 'Samak-021-01', 'Samak Pongmali', 15.59, 'ACTIVE');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (11615.0, 'PTG', 'Samak-021-02', 'Samak Pongmali', 6.49, 'ACTIVE');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (41817.0, 'PTG', 'Srinuan-018-01', 'Srinuan Ratree', 6.67, 'ACTIVE');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (36163.0, 'PTG', 'Srinuan-018-02', 'Srinuan Ratree', 3.81, 'ACTIVE');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (36160.0, 'PTG', 'Srinuan-018-03', 'Srinuan Ratree', 2.32, 'ACTIVE');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (36155.0, 'PTG', 'Srinuan-018-04', 'Srinuan Ratree', 4.46, 'ACTIVE');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (6791.0, 'PTG', 'Suphatra-035-6791', 'Suthasinee Meechana', 9.02, 'ACTIVE');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (2861.0, 'PTG', 'Suthasinee-034-01', 'Suthasinee Meechana', 10.38, 'ACTIVE');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (36167.0, 'PTG', 'Wichan-023-01', 'Wichan Amphon', 7.72, 'ACTIVE');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (16498.0, 'CPA6', 'Ratna-093-01', 'Ratna Im-saad', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (8379.0, 'CPA6', 'Ratna-093-02', 'Ratna Im-saad', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (37239.0, 'CPA6', 'Siwaphon-094-02', 'Siwaphon Salipon', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (37234.0, 'CPA6', 'Siwaphon-094-03', 'Siwaphon Salipon', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (19324.0, 'CPA6', 'Siwaphon-094-01', 'Siwaphon Salipon', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (19704.0, 'CPA6', '', '', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (3227.0, 'CPA6', '', '', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (23095.0, 'CPA6', '', '', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (3024.0, 'CPA6', '', '', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (9527.0, 'CPA6', '', '', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (3124.0, 'CPA6', '', '', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (16142.0, 'CPA6', '', '', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (13438.0, 'CPA6', 'Urai-rat-092-02', 'Urai-rat Mee-pom', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (8381.0, 'CPA6', 'Urai-rat-092-01', 'Urai-rat Mee-pom', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (8391.0, 'CPA6', 'Urai-rat-092-03', 'Urai-rat Mee-pom', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (5201.0, 'CPA3', '', '', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (37037.0, 'CPA3', '', '', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (253.0, 'CPA3', '', '', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (7278.0, 'CPA3', '', '', 0, 'Terminate');
INSERT INTO farmers (parcel_id, grouping, nzc_field_id, farmer_name, activity_area, status) VALUES (3105.0, 'CPA3', '', '', 0, 'Terminate');
