name = "awd-payment-dashboard"
compatibility_date = "2026-05-12"

[assets]
directory = "./dist"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "awd_db"
database_id = "local" 
migrations_dir = "migrations"
